name: Publish Package to npmjs
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: example

    strategy:
      matrix:
        node-version: [14.x]

    steps:

      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      # - run: echo //npm.pkg.github.com/:_authToken=${{secrets.ACCESS_TOKEN}} >> ~/.npmrc
      - run: yarn
      - run: npm run build --if-present
      - run: npm test
