name: Publish Package to npmjs
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: "Automated Version Bump"
        uses: actions/checkout@v2
        with:
          tag-prefix: ""
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - name: "Setup .npmrc file to publish to npm"
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: "https://npm.pkg.github.com"
          scope: "@akashudayan"
      - run: yarn
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}
